In [1]:
#Tensor -> PyTorch is a library for processing tenosrs.A tensor is a number,vector,matrix, or any n-dimentional array.


In [2]:
#pytorch

In [3]:
import torch

In [4]:
t1 = torch.tensor(72.2)
t1

tensor(72.2000)

In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor([12,535,2,5,])
t2

tensor([ 12, 535,   2,   5])

In [7]:
t2.dtype

torch.int64

In [8]:
# Matrix

t3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [8,9,5]
])
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 5]])

In [9]:
t3.dtype

torch.int64

In [10]:
# -> Tensors can have any number of dimensions and different lengths along each dimension. We can inspect
#  the length along each dimension using the .shape property of a tensor

In [11]:
t1

tensor(72.2000)

In [12]:
t1.shape

torch.Size([])

In [13]:
t3.shape

torch.Size([3, 3])

In [14]:
t3.size()

torch.Size([3, 3])

In [15]:
t2
t2.size()
t2.shape

torch.Size([4])

In [16]:
 t2[1]

tensor(535)

In [17]:
# --Tensor operations and gradiants

#-- > we can combine tensors with the useful operations.

In [29]:
x = torch.tensor(23)
y = torch.tensor(27.42 ,requires_grad= True)
z = torch.tensor(8.1 , requires_grad= True)
x,y,z

(tensor(23),
 tensor(27.4200, requires_grad=True),
 tensor(8.1000, requires_grad=True))

In [30]:
t = x * y / z

In [31]:
t

tensor(77.8593, grad_fn=<DivBackward0>)

In [32]:
#  To compute the derivatives , we can invoke the .backward method on our result t.

In [33]:
t.backward()

In [34]:
print('dy/dx: ' , x.grad)
print('dy/dy:' , y.grad)
print("dy/dx:  ", z.grad)


dy/dx:  None
dy/dy: tensor(2.8395)
dy/dx:   tensor(-9.6123)


In [36]:
# Create a tensor with a fixed value for every element

t6 = torch.full((2,3),19)
t6                                  # 2 row and 3 columns with number:19

tensor([[19, 19, 19],
        [19, 19, 19]])

In [37]:
# Concatenate two tensors with compatible shapes

t7 = torch.cat((t3,t6))
t7

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9,  5],
        [19, 19, 19],
        [19, 19, 19]])

In [38]:
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 5]])

In [39]:
t7

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9,  5],
        [19, 19, 19],
        [19, 19, 19]])

In [40]:
t6

tensor([[19, 19, 19],
        [19, 19, 19]])

In [45]:
#compute the sin of each element

t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.9894,  0.4121, -0.9589],
        [ 0.1499,  0.1499,  0.1499],
        [ 0.1499,  0.1499,  0.1499]])

In [50]:
t9 = t8.reshape(15,1)
t9

tensor([[ 0.8415],
        [ 0.9093],
        [ 0.1411],
        [-0.7568],
        [-0.9589],
        [-0.2794],
        [ 0.9894],
        [ 0.4121],
        [-0.9589],
        [ 0.1499],
        [ 0.1499],
        [ 0.1499],
        [ 0.1499],
        [ 0.1499],
        [ 0.1499]])

In [53]:
t9 = t8.reshape(3,5)
t9

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
        [-0.2794,  0.9894,  0.4121, -0.9589,  0.1499],
        [ 0.1499,  0.1499,  0.1499,  0.1499,  0.1499]])

In [54]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
x

array([[1, 2],
       [3, 4]])

In [55]:
# convert the numpy array to a torch tensor

y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [56]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [57]:
# convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [58]:
z.dtype

dtype('int64')